### 
GET http://localhost:3000/api/ 

###
GET http://localhost:3000/api/users/  ('Woordenlijst' kan ook gebruikt woorden in plaats van 'users')

###
GET http://localhost:3000/api/users?limit=20&offset=20

### 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{ 
    "email": "emily@example.com", 
    "password": "emilydavis123" 
}

### 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "michael@example.com",
  "password": "michealbrown456"
}
